name: "cicd"
on:
  pull_request:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - master
      - develop
    releases:
      types:

jobs:
  build:
    name: build2
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ken5scal/ecs-fargate-with-go-app/hoge
          username: ${{ github.actor }}
          password: ${{ secrets.APP_A_GITHUB_CI_CD_TOKEN }}
          registry: docker.pkg.github.com
          tag_with_ref: true
          tag_with_sha: true